import QtQuick 2.6
import QtQuick.Controls 1.5

ApplicationWindow {
    id: applicationWindow
    visible: true
    width: 640
    height: 480

    Label {
        id: helloLabel
        height: 50
        anchors {
            top: parent.top
            left: parent.left
            right: parent.horizontalCenter
            margins: 10
        }
    }

    ComboBox {
        id: comboBox
        anchors {
            top: parent.top
            left: parent.horizontalCenter
            right: parent.right
            margins: 10
        }

        model: ["ru_RU", "ko_KR"]

        // If you change the text, initialize the translation unit via C++ Layer
        onCurrentTextChanged: {
            console.log("comboBox.currentText : " , comboBox.currentText)
            qmlTranslator.setTranslation(comboBox.currentText)
        }
    }

    Label {
        id: labelText
        wrapMode: Text.Wrap
        anchors {
            top: helloLabel.bottom
            left: parent.left
            right: parent.right
            margins: 10
        }
    }

    // Connect to an interpreter object
    Connections {
        target: qmlTranslator   // was registered in main.cpp
        function onLanguageChanged() {    // upon receipt of the signal to change the language
            retranslateUi()     // initialize interface translation
        }
    }

    // interface translation function
    function retranslateUi() {
        applicationWindow.title = qsTr("Hello World")
        helloLabel.text = qsTr("Hello World")
//        labelText.text = qsTr("The QTranslator class provides internationalization" +
//                              "support for text output.An object of this class contains " +
//                              "a set of translations from a source language to a target language. " +
//                              "QTranslator provides functions to look up translations in a translation file. " +
//                              "Translation files are created using Qt Linguist.")
        console.log("@@@@@@@@@@@@@@@@@@2")
        labelText.text = qsTranslate("main","LID_0002")+"\n" +
                qsTranslate("main","LID_0004")+"\n" +
                qsTranslate("main","LID_0011")+"\n" +
                qsTranslate("main","LID_0014")+"\n" +
                qsTranslate("main","LID_0015")+"\n" +
                qsTranslate("main","LID_0016")+"\n" +
                qsTranslate("main","LID_0017")+"\n" +
                qsTranslate("main","LID_0018")+"\n" +
                qsTranslate("main","LID_0019")+"\n" +
                qsTranslate("main","LID_0020")+"\n" +
                qsTranslate("main","LID_0022")+"\n" +
                qsTranslate("main","LID_0023")+"\n" +
                qsTranslate("main","LID_0025")+"\n" +
                qsTranslate("main","LID_0026")+"\n" +
                qsTranslate("main","LID_0027")+"\n" +
                qsTranslate("main","LID_0028")+"\n" +
                qsTranslate("main","LID_0031")+"\n" +
                qsTranslate("main","LID_0033")+"\n" +
                qsTranslate("main","LID_0034")+"\n" +
                qsTranslate("main","LID_0035")+"\n" +
                qsTranslate("main","LID_0036")+"\n" +
                qsTranslate("main","LID_0037")+"\n" +
                qsTranslate("main","LID_0038")+"\n" +
                qsTranslate("main","LID_0040")+"\n" +
                qsTranslate("main","LID_0045")+"\n" +
                qsTranslate("main","LID_0047")+"\n" +
                qsTranslate("main","LID_0056")+"\n" +
                qsTranslate("main","LID_0057")+"\n" +
                qsTranslate("main","LID_0058")+"\n" +
                qsTranslate("main","LID_0060")+"\n" +
                qsTranslate("main","LID_0061")+"\n" +
                qsTranslate("main","LID_0062")+"\n" +
                qsTranslate("main","LID_0063")+"\n" +
                qsTranslate("main","LID_0065")+"\n" +
                qsTranslate("main","LID_0066")+"\n" +
                qsTranslate("main","LID_0068")+"\n" +
                qsTranslate("main","LID_0071")+"\n" +
                qsTranslate("main","LID_0072")+"\n" +
                qsTranslate("main","LID_0074")+"\n" +
                qsTranslate("main","LID_0075")+"\n" +
                qsTranslate("main","LID_0076")+"\n" +
                qsTranslate("main","LID_0077")+"\n" +
                qsTranslate("main","LID_0078")+"\n" +
                qsTranslate("main","LID_0085")+"\n" +
                qsTranslate("main","LID_0086")+"\n" +
                qsTranslate("main","LID_0088")+"\n" +
                qsTranslate("main","LID_0089")+"\n" +
                qsTranslate("main","LID_0090")+"\n" +
                qsTranslate("main","LID_0093")+"\n" +
                qsTranslate("main","LID_0096")+"\n" +
                qsTranslate("main","LID_0097")+"\n" +
                qsTranslate("main","LID_0103")+"\n" +
                qsTranslate("main","LID_0104")+"\n" +
                qsTranslate("main","LID_0105")+"\n" +
                qsTranslate("main","LID_0107")+"\n" +
                qsTranslate("main","LID_0109")+"\n" +
                qsTranslate("main","LID_0110")+"\n" +
                qsTranslate("main","LID_0111")+"\n" +
                qsTranslate("main","LID_0113")+"\n" +
                qsTranslate("main","LID_0114")+"\n" +
                qsTranslate("main","LID_0116")+"\n" +
                qsTranslate("main","LID_0117")+"\n" +
                qsTranslate("main","LID_0118")+"\n" +
                qsTranslate("main","LID_0128")+"\n" +
                qsTranslate("main","LID_0130")+"\n" +
                qsTranslate("main","LID_0132")+"\n" +
                qsTranslate("main","LID_0133")+"\n" +
                qsTranslate("main","LID_0134")+"\n" +
                qsTranslate("main","LID_0136")+"\n" +
                qsTranslate("main","LID_0137")+"\n" +
                qsTranslate("main","LID_0141")+"\n" +
                qsTranslate("main","LID_0142")+"\n" +
                qsTranslate("main","LID_0143")+"\n" +
                qsTranslate("main","LID_0148")+"\n" +
                qsTranslate("main","LID_0150")+"\n" +
                qsTranslate("main","LID_0154")+"\n" +
                qsTranslate("main","LID_0155")+"\n" +
                qsTranslate("main","LID_0157")+"\n" +
                qsTranslate("main","LID_0159")+"\n" +
                qsTranslate("main","LID_0162")+"\n" +
                qsTranslate("main","LID_0163")+"\n" +
                qsTranslate("main","LID_0169")+"\n" +
                qsTranslate("main","LID_0171")+"\n" +
                qsTranslate("main","LID_0172")+"\n" +
                qsTranslate("main","LID_0173")+"\n" +
                qsTranslate("main","LID_0174")+"\n" +
                qsTranslate("main","LID_0176")+"\n" +
                qsTranslate("main","LID_0177")+"\n" +
                qsTranslate("main","LID_0186")+"\n" +
                qsTranslate("main","LID_0199")+"\n" +
                qsTranslate("main","LID_0201")+"\n" +
                qsTranslate("main","LID_0202")+"\n" +
                qsTranslate("main","LID_0203")+"\n" +
                qsTranslate("main","LID_0204")+"\n" +
                qsTranslate("main","LID_0207")+"\n" +
                qsTranslate("main","LID_0208")+"\n" +
                qsTranslate("main","LID_0212")+"\n" +
                qsTranslate("main","LID_0213")+"\n" +
                qsTranslate("main","LID_0214")+"\n" +
                qsTranslate("main","LID_0215")+"\n" +
                qsTranslate("main","LID_0216")+"\n" +
                qsTranslate("main","LID_0218")+"\n" +
                qsTranslate("main","LID_0219")+"\n" +
                qsTranslate("main","LID_0221")+"\n" +
                qsTranslate("main","LID_0222")+"\n" +
                qsTranslate("main","LID_0224")+"\n" +
                qsTranslate("main","LID_0225")+"\n" +
                qsTranslate("main","LID_0226")+"\n" +
                qsTranslate("main","LID_0227")+"\n" +
                qsTranslate("main","LID_0229")+"\n" +
                qsTranslate("main","LID_0230")+"\n" +
                qsTranslate("main","LID_0231")+"\n" +
                qsTranslate("main","LID_0233")+"\n" +
                qsTranslate("main","LID_0234")+"\n" +
                qsTranslate("main","LID_0235")+"\n" +
                qsTranslate("main","LID_0237")+"\n" +
                qsTranslate("main","LID_0238")+"\n" +
                qsTranslate("main","LID_0239")+"\n" +
                qsTranslate("main","LID_0240")+"\n" +
                qsTranslate("main","LID_0241")+"\n" +
                qsTranslate("main","LID_0242")+"\n" +
                qsTranslate("main","LID_0243")+"\n" +
                qsTranslate("main","LID_0244")+"\n" +
                qsTranslate("main","LID_0245")+"\n" +
                qsTranslate("main","LID_0253")+"\n" +
                qsTranslate("main","LID_0259")+"\n" +
                qsTranslate("main","LID_0262")+"\n" +
                qsTranslate("main","LID_0263")+"\n" +
                qsTranslate("main","LID_0265")+"\n" +
                qsTranslate("main","LID_0272")+"\n" +
                qsTranslate("main","LID_0273")+"\n" +
                qsTranslate("main","LID_0274")+"\n" +
                qsTranslate("main","LID_0275")+"\n" +
                qsTranslate("main","LID_0277")+"\n" +
                qsTranslate("main","LID_0278")+"\n" +
                qsTranslate("main","LID_0279")+"\n" +
                qsTranslate("main","LID_0285")+"\n" +
                qsTranslate("main","LID_0288")+"\n" +
                qsTranslate("main","LID_0292")+"\n" +
                qsTranslate("main","LID_0295")+"\n" +
                qsTranslate("main","LID_0296")+"\n" +
                qsTranslate("main","LID_0297")+"\n" +
                qsTranslate("main","LID_0298")+"\n" +
                qsTranslate("main","LID_0299")+"\n" +
                qsTranslate("main","LID_0302")+"\n" +
                qsTranslate("main","LID_0303")+"\n" +
                qsTranslate("main","LID_0304")+"\n" +
                qsTranslate("main","LID_0309")+"\n" +
                qsTranslate("main","LID_0311")+"\n" +
                qsTranslate("main","LID_0312")+"\n" +
                qsTranslate("main","LID_0313")+"\n" +
                qsTranslate("main","LID_0314")+"\n" +
                qsTranslate("main","LID_0315")+"\n" +
                qsTranslate("main","LID_0318")+"\n" +
                qsTranslate("main","LID_0323")+"\n" +
                qsTranslate("main","LID_0331")+"\n" +
                qsTranslate("main","LID_0332")+"\n" +
                qsTranslate("main","LID_0337")+"\n" +
                qsTranslate("main","LID_0339")+"\n" +
                qsTranslate("main","LID_0340")+"\n" +
                qsTranslate("main","LID_0341")+"\n" +
                qsTranslate("main","LID_0343")+"\n" +
                qsTranslate("main","LID_0348")+"\n" +
                qsTranslate("main","LID_0351")+"\n" +
                qsTranslate("main","LID_0353")+"\n" +
                qsTranslate("main","LID_0358")+"\n" +
                qsTranslate("main","LID_0359")+"\n" +
                qsTranslate("main","LID_0362")+"\n" +
                qsTranslate("main","LID_0365")+"\n" +
                qsTranslate("main","LID_0366")+"\n" +
                qsTranslate("main","LID_0367")+"\n" +
                qsTranslate("main","LID_0368")+"\n" +
                qsTranslate("main","LID_0370")+"\n" +
                qsTranslate("main","LID_0372")+"\n" +
                qsTranslate("main","LID_0373")+"\n" +
                qsTranslate("main","LID_0374")+"\n" +
                qsTranslate("main","LID_0375")+"\n" +
                qsTranslate("main","LID_0377")+"\n" +
                qsTranslate("main","LID_0384")+"\n" +
                qsTranslate("main","LID_0385")+"\n" +
                qsTranslate("main","LID_0393")+"\n" +
                qsTranslate("main","LID_0395")+"\n" +
                qsTranslate("main","LID_0396")+"\n" +
                qsTranslate("main","LID_0397")+"\n" +
                qsTranslate("main","LID_0400")+"\n" +
                qsTranslate("main","LID_0402")+"\n" +
                qsTranslate("main","LID_0405")+"\n" +
                qsTranslate("main","LID_0406")+"\n" +
                qsTranslate("main","LID_0407")+"\n" +
                qsTranslate("main","LID_0408")+"\n" +
                qsTranslate("main","LID_0419")+"\n" +
                qsTranslate("main","LID_0427")+"\n" +
                qsTranslate("main","LID_0433")+"\n" +
                qsTranslate("main","LID_0434")+"\n" +
                qsTranslate("main","LID_0435")+"\n" +
                qsTranslate("main","LID_0436")+"\n" +
                qsTranslate("main","LID_0437")+"\n" +
                qsTranslate("main","LID_0438")+"\n" +
                qsTranslate("main","LID_0439")+"\n" +
                qsTranslate("main","LID_0442")+"\n" +
                qsTranslate("main","LID_0445")+"\n" +
                qsTranslate("main","LID_0446")+"\n" +
                qsTranslate("main","LID_0447")+"\n" +
                qsTranslate("main","LID_0448")+"\n" +
                qsTranslate("main","LID_0450")+"\n" +
                qsTranslate("main","LID_0451")+"\n" +
                qsTranslate("main","LID_0453")+"\n" +
                qsTranslate("main","LID_0454")+"\n" +
                qsTranslate("main","LID_0456")+"\n" +
                qsTranslate("main","LID_0458")+"\n" +
                qsTranslate("main","LID_0459")+"\n" +
                qsTranslate("main","LID_0461")+"\n" +
                qsTranslate("main","LID_0462")+"\n" +
                qsTranslate("main","LID_0463")+"\n" +
                qsTranslate("main","LID_0464")+"\n" +
                qsTranslate("main","LID_0469")+"\n" +
                qsTranslate("main","LID_0470")+"\n" +
                qsTranslate("main","LID_0471")+"\n" +
                qsTranslate("main","LID_0472")+"\n" +
                qsTranslate("main","LID_0474")+"\n" +
                qsTranslate("main","LID_0475")+"\n" +
                qsTranslate("main","LID_0476")+"\n" +
                qsTranslate("main","LID_0477")+"\n" +
                qsTranslate("main","LID_0478")+"\n" +
                qsTranslate("main","LID_0479")+"\n" +
                qsTranslate("main","LID_0488")+"\n" +
                qsTranslate("main","LID_0493")+"\n" +
                qsTranslate("main","LID_0494")+"\n" +
                qsTranslate("main","LID_0495")+"\n" +
                qsTranslate("main","LID_0500")+"\n" +
                qsTranslate("main","LID_0501")+"\n" +
                qsTranslate("main","LID_0502")+"\n" +
                qsTranslate("main","LID_0503")+"\n" +
                qsTranslate("main","LID_0504")+"\n" +
                qsTranslate("main","LID_0505")+"\n" +
                qsTranslate("main","LID_0506")+"\n" +
                qsTranslate("main","LID_0508")+"\n" +
                qsTranslate("main","LID_0512")+"\n" +
                qsTranslate("main","LID_0513")+"\n" +
                qsTranslate("main","LID_0515")+"\n" +
                qsTranslate("main","LID_0517")+"\n" +
                qsTranslate("main","LID_0518")+"\n" +
                qsTranslate("main","LID_0519")+"\n" +
                qsTranslate("main","LID_0520")+"\n" +
                qsTranslate("main","LID_0521")+"\n" +
                qsTranslate("main","LID_0522")+"\n" +
                qsTranslate("main","LID_0524")+"\n" +
                qsTranslate("main","LID_0525")+"\n" +
                qsTranslate("main","LID_0528")+"\n" +
                qsTranslate("main","LID_0529")+"\n" +
                qsTranslate("main","LID_0535")+"\n" +
                qsTranslate("main","LID_0537")+"\n" +
                qsTranslate("main","LID_0538")+"\n" +
                qsTranslate("main","LID_0539")+"\n" +
                qsTranslate("main","LID_0540")+"\n" +
                qsTranslate("main","LID_0541")+"\n" +
                qsTranslate("main","LID_0542")+"\n" +
                qsTranslate("main","LID_0543")+"\n" +
                qsTranslate("main","LID_0544")+"\n" +
                qsTranslate("main","LID_0546")+"\n" +
                qsTranslate("main","LID_0547")+"\n" +
                qsTranslate("main","LID_0548")+"\n" +
                qsTranslate("main","LID_0549")+"\n" +
                qsTranslate("main","LID_0550")+"\n" +
                qsTranslate("main","LID_0551")+"\n" +
                qsTranslate("main","LID_0552")+"\n" +
                qsTranslate("main","LID_0553")+"\n" +
                qsTranslate("main","LID_0555")+"\n" +
                qsTranslate("main","LID_0559")+"\n" +
                qsTranslate("main","LID_0560")+"\n" +
                qsTranslate("main","LID_0561")+"\n" +
                qsTranslate("main","LID_0562")+"\n" +
                qsTranslate("main","LID_0563")+"\n" +
                qsTranslate("main","LID_0564")+"\n" +
                qsTranslate("main","LID_0565")+"\n" +
                qsTranslate("main","LID_0566")+"\n" +
                qsTranslate("main","LID_0567")+"\n" +
                qsTranslate("main","LID_0568")+"\n" +
                qsTranslate("main","LID_0571")+"\n" +
                qsTranslate("main","LID_0572")+"\n" +
                qsTranslate("main","LID_0573")+"\n" +
                qsTranslate("main","LID_0574")+"\n" +
                qsTranslate("main","LID_0575")+"\n" +
                qsTranslate("main","LID_0577")+"\n" +
                qsTranslate("main","LID_0578")+"\n" +
                qsTranslate("main","LID_0580")+"\n" +
                qsTranslate("main","LID_0581")+"\n" +
                qsTranslate("main","LID_0583")+"\n" +
                qsTranslate("main","LID_0584")+"\n" +
                qsTranslate("main","LID_0586")+"\n" +
                qsTranslate("main","LID_0587")+"\n" +
                qsTranslate("main","LID_0588")+"\n" +
                qsTranslate("main","LID_0589")+"\n" +
                qsTranslate("main","LID_0590")+"\n" +
                qsTranslate("main","LID_0591")+"\n" +
                qsTranslate("main","LID_0592")+"\n" +
                qsTranslate("main","LID_0593")+"\n" +
                qsTranslate("main","LID_0594")+"\n" +
                qsTranslate("main","LID_0595")+"\n" +
                qsTranslate("main","LID_0601")+"\n" +
                qsTranslate("main","LID_0603")+"\n" +
                qsTranslate("main","LID_0604")+"\n" +
                qsTranslate("main","LID_0605")+"\n" +
                qsTranslate("main","LID_0608")+"\n" +
                qsTranslate("main","LID_0610")+"\n" +
                qsTranslate("main","LID_0613")+"\n" +
                qsTranslate("main","LID_0614")+"\n" +
                qsTranslate("main","LID_0615")+"\n" +
                qsTranslate("main","LID_0616")+"\n" +
                qsTranslate("main","LID_0617")+"\n" +
                qsTranslate("main","LID_0618")+"\n" +
                qsTranslate("main","LID_0619")+"\n" +
                qsTranslate("main","LID_0623")+"\n" +
                qsTranslate("main","LID_0624")+"\n" +
                qsTranslate("main","LID_0625")+"\n" +
                qsTranslate("main","LID_0631")+"\n" +
                qsTranslate("main","LID_0632")+"\n" +
                qsTranslate("main","LID_0633")+"\n" +
                qsTranslate("main","LID_0634")+"\n" +
                qsTranslate("main","LID_0635")+"\n" +
                qsTranslate("main","LID_0636")+"\n" +
                qsTranslate("main","LID_0637")+"\n" +
                qsTranslate("main","LID_0638")+"\n" +
                qsTranslate("main","LID_0642")+"\n" +
                qsTranslate("main","LID_0643")+"\n" +
                qsTranslate("main","LID_0644")+"\n" +
                qsTranslate("main","LID_0645")+"\n" +
                qsTranslate("main","LID_0646")+"\n" +
                qsTranslate("main","LID_0647")+"\n" +
                qsTranslate("main","LID_0652")+"\n" +
                qsTranslate("main","LID_0653")+"\n" +
                qsTranslate("main","LID_0654")+"\n" +
                qsTranslate("main","LID_0655")+"\n" +
                qsTranslate("main","LID_0656")+"\n" +
                qsTranslate("main","LID_0659")+"\n" +
                qsTranslate("main","LID_0676")+"\n" +
                qsTranslate("main","LID_0678")+"\n" +
                qsTranslate("main","LID_0679")+"\n" +
                qsTranslate("main","LID_0680")+"\n" +
                qsTranslate("main","LID_0689")+"\n" +
                qsTranslate("main","LID_0694")+"\n" +
                qsTranslate("main","LID_0695")+"\n" +
                qsTranslate("main","LID_0696")+"\n" +
                qsTranslate("main","LID_0698")+"\n" +
                qsTranslate("main","LID_0699")+"\n" +
                qsTranslate("main","LID_0700")+"\n" +
                qsTranslate("main","LID_0701")+"\n" +
                qsTranslate("main","LID_0703")+"\n" +
                qsTranslate("main","LID_0704")+"\n" +
                qsTranslate("main","LID_0708")+"\n" +
                qsTranslate("main","LID_0709")+"\n" +
                qsTranslate("main","LID_0710")+"\n" +
                qsTranslate("main","LID_0711")+"\n" +
                qsTranslate("main","LID_0712")+"\n" +
                qsTranslate("main","LID_0713")+"\n" +
                qsTranslate("main","LID_0720")+"\n" +
                qsTranslate("main","LID_0721")+"\n" +
                qsTranslate("main","LID_0722")+"\n" +
                qsTranslate("main","LID_0723")+"\n" +
                qsTranslate("main","LID_0729")+"\n" +
                qsTranslate("main","LID_0730")+"\n" +
                qsTranslate("main","LID_0733")+"\n" +
                qsTranslate("main","LID_0734")+"\n" +
                qsTranslate("main","LID_0735")+"\n" +
                qsTranslate("main","LID_0736")+"\n" +
                qsTranslate("main","LID_0737")+"\n" +
                qsTranslate("main","LID_0738")+"\n" +
                qsTranslate("main","LID_0739")+"\n" +
                qsTranslate("main","LID_0741")+"\n" +
                qsTranslate("main","LID_0742")+"\n" +
                qsTranslate("main","LID_0746")+"\n" +
                qsTranslate("main","LID_0747")+"\n" +
                qsTranslate("main","LID_0748")+"\n" +
                qsTranslate("main","LID_0749")+"\n" +
                qsTranslate("main","LID_0753")+"\n" +
                qsTranslate("main","LID_0754")+"\n" +
                qsTranslate("main","LID_0755")+"\n" +
                qsTranslate("main","LID_0759")+"\n" +
                qsTranslate("main","LID_0760")+"\n" +
                qsTranslate("main","LID_0763")+"\n" +
                qsTranslate("main","LID_0764")+"\n" +
                qsTranslate("main","LID_0765")+"\n" +
                qsTranslate("main","LID_0766")+"\n" +
                qsTranslate("main","LID_0767")+"\n" +
                qsTranslate("main","LID_0768")+"\n" +
                qsTranslate("main","LID_0769")+"\n" +
                qsTranslate("main","LID_0770")+"\n" +
                qsTranslate("main","LID_0772")+"\n" +
                qsTranslate("main","LID_0787")+"\n" +
                qsTranslate("main","LID_0789")+"\n" +
                qsTranslate("main","LID_0795")+"\n" +
                qsTranslate("main","LID_0796")+"\n" +
                qsTranslate("main","LID_0797")+"\n" +
                qsTranslate("main","LID_0798")+"\n" +
                qsTranslate("main","LID_0799")+"\n" +
                qsTranslate("main","LID_0800")+"\n" +
                qsTranslate("main","LID_0801")+"\n" +
                qsTranslate("main","LID_0802")+"\n" +
                qsTranslate("main","LID_0817")+"\n" +
                qsTranslate("main","LID_0818")+"\n" +
                qsTranslate("main","LID_0819")+"\n" +
                qsTranslate("main","LID_0824")+"\n" +
                qsTranslate("main","LID_0826")+"\n" +
                qsTranslate("main","LID_0828")+"\n" +
                qsTranslate("main","LID_0829")+"\n" +
                qsTranslate("main","LID_0830")+"\n" +
                qsTranslate("main","LID_0831")+"\n" +
                qsTranslate("main","LID_0834")+"\n" +
                qsTranslate("main","LID_0837")+"\n" +
                qsTranslate("main","LID_0838")+"\n" +
                qsTranslate("main","LID_0839")+"\n" +
                qsTranslate("main","LID_0840")+"\n" +
                qsTranslate("main","LID_0844")+"\n" +
                qsTranslate("main","LID_0845")+"\n" +
                qsTranslate("main","LID_0846")+"\n" +
                qsTranslate("main","LID_0849")+"\n" +
                qsTranslate("main","LID_0850")+"\n" +
                qsTranslate("main","LID_0851")+"\n" +
                qsTranslate("main","LID_0853")+"\n" +
                qsTranslate("main","LID_0854")+"\n" +
                qsTranslate("main","LID_0856")+"\n" +
                qsTranslate("main","LID_0857")+"\n" +
                qsTranslate("main","LID_0859")+"\n" +
                qsTranslate("main","LID_0860")+"\n" +
                qsTranslate("main","LID_0861")+"\n" +
                qsTranslate("main","LID_0862")+"\n" +
                qsTranslate("main","LID_0863")+"\n" +
                qsTranslate("main","LID_0864")+"\n" +
                qsTranslate("main","LID_0865")+"\n" +
                qsTranslate("main","LID_0866")+"\n" +
                qsTranslate("main","LID_0867")+"\n" +
                qsTranslate("main","LID_0868")+"\n" +
                qsTranslate("main","LID_0869")+"\n" +
                qsTranslate("main","LID_0870")+"\n" +
                qsTranslate("main","LID_0874")+"\n" +
                qsTranslate("main","LID_0875")+"\n" +
                qsTranslate("main","LID_0877")+"\n" +
                qsTranslate("main","LID_0878")+"\n" +
                qsTranslate("main","LID_0879")+"\n" +
                qsTranslate("main","LID_0883")+"\n" +
                qsTranslate("main","LID_0885")+"\n" +
                qsTranslate("main","LID_0886")+"\n" +
                qsTranslate("main","LID_0887")+"\n" +
                qsTranslate("main","LID_0888")+"\n" +
                qsTranslate("main","LID_0891")+"\n" +
                qsTranslate("main","LID_0892")+"\n" +
                qsTranslate("main","LID_0893")+"\n" +
                qsTranslate("main","LID_0894")+"\n" +
                qsTranslate("main","LID_0895")+"\n" +
                qsTranslate("main","LID_0896")+"\n" +
                qsTranslate("main","LID_0897")+"\n" +
                qsTranslate("main","LID_0899")+"\n" +
                qsTranslate("main","LID_0900")+"\n" +
                qsTranslate("main","LID_0902")+"\n" +
                qsTranslate("main","LID_0904")+"\n" +
                qsTranslate("main","LID_0907")+"\n" +
                qsTranslate("main","LID_0908")+"\n" +
                qsTranslate("main","LID_0909")+"\n" +
                qsTranslate("main","LID_0910")+"\n" +
                qsTranslate("main","LID_0911")+"\n" +
                qsTranslate("main","LID_0913")+"\n" +
                qsTranslate("main","LID_0915")+"\n" +
                qsTranslate("main","LID_0922")+"\n" +
                qsTranslate("main","LID_0923")+"\n" +
                qsTranslate("main","LID_0925")+"\n" +
                qsTranslate("main","LID_0926")+"\n" +
                qsTranslate("main","LID_0927")+"\n" +
                qsTranslate("main","LID_0928")+"\n" +
                qsTranslate("main","LID_0941")+"\n" +
                qsTranslate("main","LID_0942")+"\n" +
                qsTranslate("main","LID_0945")+"\n" +
                qsTranslate("main","LID_0946")+"\n" +
                qsTranslate("main","LID_0947")+"\n" +
                qsTranslate("main","LID_0948")+"\n" +
                qsTranslate("main","LID_0949")+"\n" +
                qsTranslate("main","LID_0950")+"\n" +
                qsTranslate("main","LID_0951")+"\n" +
                qsTranslate("main","LID_0952")+"\n" +
                qsTranslate("main","LID_0953")+"\n" +
                qsTranslate("main","LID_0954")+"\n" +
                qsTranslate("main","LID_0955")+"\n" +
                qsTranslate("main","LID_0956")+"\n" +
                qsTranslate("main","LID_0957")+"\n" +
                qsTranslate("main","LID_0958")+"\n" +
                qsTranslate("main","LID_0961")+"\n" +
                qsTranslate("main","LID_0962")+"\n" +
                qsTranslate("main","LID_0963")+"\n" +
                qsTranslate("main","LID_0964")+"\n" +
                qsTranslate("main","LID_0965")+"\n" +
                qsTranslate("main","LID_0966")+"\n" +
                qsTranslate("main","LID_0967")+"\n" +
                qsTranslate("main","LID_0968")+"\n" +
                qsTranslate("main","LID_0969")+"\n" +
                qsTranslate("main","LID_0970")+"\n" +
                qsTranslate("main","LID_0972")+"\n" +
                qsTranslate("main","LID_0974")+"\n" +
                qsTranslate("main","LID_0975")+"\n" +
                qsTranslate("main","LID_0976")+"\n" +
                qsTranslate("main","LID_0977")+"\n" +
                qsTranslate("main","LID_0978")+"\n" +
                qsTranslate("main","LID_0979")+"\n" +
                qsTranslate("main","LID_0980")+"\n" +
                qsTranslate("main","LID_0981")+"\n" +
                qsTranslate("main","LID_0982")+"\n" +
                qsTranslate("main","LID_0983")+"\n" +
                qsTranslate("main","LID_0984")+"\n" +
                qsTranslate("main","LID_0985")+"\n" +
                qsTranslate("main","LID_0986")+"\n" +
                qsTranslate("main","LID_0988")+"\n" +
                qsTranslate("main","LID_0989")+"\n" +
                qsTranslate("main","LID_0990")+"\n" +
                qsTranslate("main","LID_0991")+"\n" +
                qsTranslate("main","LID_0992")+"\n" +
                qsTranslate("main","LID_0993")+"\n" +
                qsTranslate("main","LID_0994")+"\n" +
                qsTranslate("main","LID_0995")+"\n" +
                qsTranslate("main","LID_0996")+"\n" +
                qsTranslate("main","LID_0997")+"\n" +
                qsTranslate("main","LID_0998")+"\n" +
                qsTranslate("main","LID_0999")+"\n" +
                qsTranslate("main","LID_1000")+"\n" +
                qsTranslate("main","LID_1001")+"\n" +
                qsTranslate("main","LID_1002")+"\n" +
                qsTranslate("main","LID_1003")+"\n" +
                qsTranslate("main","LID_1004")+"\n" +
                qsTranslate("main","LID_1005")+"\n" +
                qsTranslate("main","LID_1006")+"\n" +
                qsTranslate("main","LID_1007")+"\n" +
                qsTranslate("main","LID_1008")+"\n" +
                qsTranslate("main","LID_1009")+"\n" +
                qsTranslate("main","LID_1010")+"\n" +
                qsTranslate("main","LID_1011")+"\n" +
                qsTranslate("main","LID_1012")+"\n" +
                qsTranslate("main","LID_1013")+"\n" +
                qsTranslate("main","LID_1015")+"\n" +
                qsTranslate("main","LID_1016")+"\n" +
                qsTranslate("main","LID_1017")+"\n" +
                qsTranslate("main","LID_1018")+"\n" +
                qsTranslate("main","LID_1019")+"\n" +
                qsTranslate("main","LID_1020")+"\n" +
                qsTranslate("main","LID_1021")+"\n" +
                qsTranslate("main","LID_1022")+"\n" +
                qsTranslate("main","LID_1023")+"\n" +
                qsTranslate("main","LID_1024")+"\n" +
                qsTranslate("main","LID_1025")+"\n" +
                qsTranslate("main","LID_1026")+"\n" +
                qsTranslate("main","LID_1027")+"\n" +
                qsTranslate("main","LID_1028")+"\n" +
                qsTranslate("main","LID_1029")+"\n" +
                qsTranslate("main","LID_1030")+"\n" +
                qsTranslate("main","LID_1031")+"\n" +
                qsTranslate("main","LID_1032")+"\n" +
                qsTranslate("main","LID_1033")+"\n" +
                qsTranslate("main","LID_1034")+"\n" +
                qsTranslate("main","LID_1035")+"\n" +
                qsTranslate("main","LID_1036")+"\n" +
                qsTranslate("main","LID_1037")+"\n" +
                qsTranslate("main","LID_1038")+"\n" +
                qsTranslate("main","LID_1039")+"\n" +
                qsTranslate("main","LID_1040")+"\n" +
                qsTranslate("main","LID_1041")+"\n" +
                qsTranslate("main","LID_1042")+"\n" +
                qsTranslate("main","LID_1044")+"\n" +
                qsTranslate("main","LID_1045")+"\n" +
                qsTranslate("main","LID_1046")+"\n" +
                qsTranslate("main","LID_1048")+"\n" +
                qsTranslate("main","LID_1049")+"\n" +
                qsTranslate("main","LID_1050")+"\n" +
                qsTranslate("main","LID_1051")+"\n" +
                qsTranslate("main","LID_1052")+"\n" +
                qsTranslate("main","LID_1053")+"\n" +
                qsTranslate("main","LID_1054")+"\n" +
                qsTranslate("main","LID_1055")+"\n" +
                qsTranslate("main","LID_1056")+"\n" +
                qsTranslate("main","LID_1057")+"\n" +
                qsTranslate("main","LID_1058")+"\n" +
                qsTranslate("main","LID_1059")+"\n" +
                qsTranslate("main","LID_1060")+"\n" +
                qsTranslate("main","LID_1061")+"\n" +
                qsTranslate("main","LID_1062")+"\n" +
                qsTranslate("main","LID_1063")+"\n" +
                qsTranslate("main","LID_1065")+"\n" +
                qsTranslate("main","LID_1066")+"\n" +
                qsTranslate("main","LID_1067")+"\n" +
                qsTranslate("main","LID_1068")+"\n" +
                qsTranslate("main","LID_1069")+"\n" +
                qsTranslate("main","LID_1070")+"\n" +
                qsTranslate("main","LID_1071")+"\n" +
                qsTranslate("main","LID_1072")+"\n" +
                qsTranslate("main","LID_1073")+"\n" +
                qsTranslate("main","LID_1074")+"\n" +
                qsTranslate("main","LID_1075")+"\n" +
                qsTranslate("main","LID_1076")+"\n" +
                qsTranslate("main","LID_1077")+"\n" +
                qsTranslate("main","LID_1078")+"\n" +
                qsTranslate("main","LID_1079")+"\n" +
                qsTranslate("main","LID_1080")+"\n" +
                qsTranslate("main","LID_1081")+"\n" +
                qsTranslate("main","LID_1082")+"\n" +
                qsTranslate("main","LID_1083")+"\n" +
                qsTranslate("main","LID_1085")+"\n" +
                qsTranslate("main","LID_1086")+"\n" +
                qsTranslate("main","LID_1087")+"\n" +
                qsTranslate("main","LID_1093")+"\n" +
                qsTranslate("main","LID_1094")+"\n" +
                qsTranslate("main","LID_1095")+"\n" +
                qsTranslate("main","LID_1096")+"\n" +
                qsTranslate("main","LID_1101")+"\n" +
                qsTranslate("main","LID_1109")+"\n" +
                qsTranslate("main","LID_1110")+"\n" +
                qsTranslate("main","LID_1112")+"\n" +
                qsTranslate("main","LID_1114")+"\n" +
                qsTranslate("main","LID_1116")+"\n" +
                qsTranslate("main","LID_1123")+"\n" +
                qsTranslate("main","LID_1125")+"\n" +
                qsTranslate("main","LID_1126")+"\n" +
                qsTranslate("main","LID_1127")+"\n" +
                qsTranslate("main","LID_1128")+"\n" +
                qsTranslate("main","LID_1129")+"\n" +
                qsTranslate("main","LID_1130")+"\n" +
                qsTranslate("main","LID_1131")+"\n" +
                qsTranslate("main","LID_1132")+"\n" +
                qsTranslate("main","LID_1136")+"\n" +
                qsTranslate("main","LID_1137")+"\n" +
                qsTranslate("main","LID_1138")+"\n" +
                qsTranslate("main","LID_1139")+"\n" +
                qsTranslate("main","LID_1140")+"\n" +
                qsTranslate("main","LID_1141")+"\n" +
                qsTranslate("main","LID_1143")+"\n" +
                qsTranslate("main","LID_1144")+"\n" +
                qsTranslate("main","LID_1145")+"\n" +
                qsTranslate("main","LID_1146")+"\n" +
                qsTranslate("main","LID_1147")+"\n" +
                qsTranslate("main","LID_1148")+"\n" +
                qsTranslate("main","LID_1149")+"\n" +
                qsTranslate("main","LID_1150")+"\n" +
                qsTranslate("main","LID_1151")+"\n" +
                qsTranslate("main","LID_1152")+"\n" +
                qsTranslate("main","LID_1153")+"\n" +
                qsTranslate("main","LID_1154")+"\n" +
                qsTranslate("main","LID_1155")+"\n" +
                qsTranslate("main","LID_1156")+"\n" +
                qsTranslate("main","LID_1157")+"\n" +
                qsTranslate("main","LID_1158")+"\n" +
                qsTranslate("main","LID_1159")+"\n" +
                qsTranslate("main","LID_1160")+"\n" +
                qsTranslate("main","LID_1161")+"\n" +
                qsTranslate("main","LID_1162")+"\n" +
                qsTranslate("main","LID_1163")+"\n" +
                qsTranslate("main","LID_1164")+"\n" +
                qsTranslate("main","LID_1165")+"\n" +
                qsTranslate("main","LID_1166")+"\n" +
                qsTranslate("main","LID_1167")+"\n" +
                qsTranslate("main","LID_1169")+"\n" +
                qsTranslate("main","LID_1171")+"\n" +
                qsTranslate("main","LID_1172")+"\n" +
                qsTranslate("main","LID_1173")+"\n" +
                qsTranslate("main","LID_1174")+"\n" +
                qsTranslate("main","LID_1175")+"\n" +
                qsTranslate("main","LID_1176")+"\n" +
                qsTranslate("main","LID_1177")+"\n" +
                qsTranslate("main","LID_1178")+"\n" +
                qsTranslate("main","LID_1179")+"\n" +
                qsTranslate("main","LID_1180")+"\n" +
                qsTranslate("main","LID_1181")+"\n" +
                qsTranslate("main","LID_1182")+"\n" +
                qsTranslate("main","LID_1185")+"\n" +
                qsTranslate("main","LID_1186")+"\n" +
                qsTranslate("main","LID_1187")+"\n" +
                qsTranslate("main","LID_1188")+"\n" +
                qsTranslate("main","LID_1189")+"\n" +
                qsTranslate("main","LID_1190")+"\n" +
                qsTranslate("main","LID_1191")+"\n" +
                qsTranslate("main","LID_1192")+"\n" +
                qsTranslate("main","LID_1193")+"\n" +
                qsTranslate("main","LID_1194")+"\n" +
                qsTranslate("main","LID_1195")+"\n" +
                qsTranslate("main","LID_1196")+"\n" +
                qsTranslate("main","LID_1197")+"\n" +
                qsTranslate("main","LID_1198")+"\n" +
                qsTranslate("main","LID_1199")+"\n" +
                qsTranslate("main","LID_1200")+"\n" +
                qsTranslate("main","LID_1201")+"\n" +
                qsTranslate("main","LID_1202")+"\n" +
                qsTranslate("main","LID_1203")+"\n" +
                qsTranslate("main","LID_1204")+"\n" +
                qsTranslate("main","LID_1205")+"\n" +
                qsTranslate("main","LID_1206")+"\n" +
                qsTranslate("main","LID_1210")+"\n" +
                qsTranslate("main","LID_1211")+"\n" +
                qsTranslate("main","LID_1212")+"\n" +
                qsTranslate("main","LID_1213")+"\n" +
                qsTranslate("main","LID_1214")+"\n" +
                qsTranslate("main","LID_1221")+"\n" +
                qsTranslate("main","LID_1222")+"\n" +
                qsTranslate("main","LID_1223")+"\n" +
                qsTranslate("main","LID_1224")+"\n" +
                qsTranslate("main","LID_1225")+"\n" +
                qsTranslate("main","LID_1226")+"\n" +
                qsTranslate("main","LID_1227")+"\n" +
                qsTranslate("main","LID_1228")+"\n" +
                qsTranslate("main","LID_1229")+"\n" +
                qsTranslate("main","LID_1230")+"\n" +
                qsTranslate("main","LID_1231")+"\n" +
                qsTranslate("main","LID_1232")+"\n" +
                qsTranslate("main","LID_1233")+"\n" +
                qsTranslate("main","LID_1234")+"\n" +
                qsTranslate("main","LID_1235")+"\n" +
                qsTranslate("main","LID_1236")+"\n" +
                qsTranslate("main","LID_1237")+"\n" +
                qsTranslate("main","LID_1238")+"\n" +
                qsTranslate("main","LID_1239")+"\n" +
                qsTranslate("main","LID_1241")+"\n" +
                qsTranslate("main","LID_1242")+"\n" +
                qsTranslate("main","LID_1243")+"\n" +
                qsTranslate("main","LID_1244")+"\n" +
                qsTranslate("main","LID_1245")+"\n" +
                qsTranslate("main","LID_1246")+"\n" +
                qsTranslate("main","LID_1247")+"\n" +
                qsTranslate("main","LID_1248")+"\n" +
                qsTranslate("main","LID_1249")+"\n" +
                qsTranslate("main","LID_1250")+"\n" +
                qsTranslate("main","LID_1251")+"\n" +
                qsTranslate("main","LID_1252")+"\n" +
                qsTranslate("main","LID_1253")+"\n" +
                qsTranslate("main","LID_1254")+"\n" +
                qsTranslate("main","LID_1255")+"\n" +
                qsTranslate("main","LID_1256")+"\n" +
                qsTranslate("main","LID_1257")+"\n" +
                qsTranslate("main","LID_1258")+"\n" +
                qsTranslate("main","LID_1259")+"\n" +
                qsTranslate("main","LID_1261")+"\n" +
                qsTranslate("main","LID_1262")+"\n" +
                qsTranslate("main","LID_1263")+"\n" +
                qsTranslate("main","LID_1264")+"\n" +
                qsTranslate("main","LID_1265")+"\n" +
                qsTranslate("main","LID_1266")+"\n" +
                qsTranslate("main","LID_1267")+"\n" +
                qsTranslate("main","LID_1268")+"\n" +
                qsTranslate("main","LID_1269")+"\n" +
                qsTranslate("main","LID_1270")+"\n" +
                qsTranslate("main","LID_1272")+"\n" +
                qsTranslate("main","LID_1273")+"\n" +
                qsTranslate("main","LID_1274")+"\n" +
                qsTranslate("main","LID_1275")+"\n" +
                qsTranslate("main","LID_1276")+"\n" +
                qsTranslate("main","LID_1277")+"\n" +
                qsTranslate("main","LID_1278")+"\n" +
                qsTranslate("main","LID_1279")+"\n" +
                qsTranslate("main","LID_1280")+"\n" +
                qsTranslate("main","LID_1281")+"\n" +
                qsTranslate("main","LID_1282")+"\n" +
                qsTranslate("main","LID_1283")+"\n" +
                qsTranslate("main","LID_1284")+"\n" +
                qsTranslate("main","LID_1285")+"\n" +
                qsTranslate("main","LID_1286")+"\n" +
                qsTranslate("main","LID_1287")+"\n" +
                qsTranslate("main","LID_1288")+"\n" +
                qsTranslate("main","LID_1291")+"\n" +
                qsTranslate("main","LID_1292")+"\n" +
                qsTranslate("main","LID_1293")+"\n" +
                qsTranslate("main","LID_1294")+"\n" +
                qsTranslate("main","LID_1295")+"\n" +
                qsTranslate("main","LID_1296")+"\n" +
                qsTranslate("main","LID_1297")+"\n" +
                qsTranslate("main","LID_1298")+"\n" +
                qsTranslate("main","LID_1299")+"\n" +
                qsTranslate("main","LID_1300")+"\n" +
                qsTranslate("main","LID_1301")+"\n" +
                qsTranslate("main","LID_1302")+"\n" +
                qsTranslate("main","LID_1303")+"\n" +
                qsTranslate("main","LID_1304")+"\n" +
                qsTranslate("main","LID_1305")+"\n" +
                qsTranslate("main","LID_1306")+"\n" +
                qsTranslate("main","LID_1307")+"\n" +
                qsTranslate("main","LID_1308")+"\n" +
                qsTranslate("main","LID_1311")+"\n" +
                qsTranslate("main","LID_1312")+"\n" +
                qsTranslate("main","LID_1313")+"\n" +
                qsTranslate("main","LID_1314")+"\n" +
                qsTranslate("main","LID_1315")+"\n" +
                qsTranslate("main","LID_1316")+"\n" +
                qsTranslate("main","LID_1317")+"\n" +
                qsTranslate("main","LID_1318")+"\n" +
                qsTranslate("main","LID_1319")+"\n" +
                qsTranslate("main","LID_1320")+"\n" +
                qsTranslate("main","LID_1321")+"\n" +
                qsTranslate("main","LID_1322")+"\n" +
                qsTranslate("main","LID_1323")+"\n" +
                qsTranslate("main","LID_1324")+"\n" +
                qsTranslate("main","LID_1325")+"\n" +
                qsTranslate("main","LID_1326")+"\n" +
                qsTranslate("main","LID_1327")+"\n" +
                qsTranslate("main","LID_1328")+"\n" +
                qsTranslate("main","LID_1329")+"\n" +
                qsTranslate("main","LID_1330")+"\n" +
                qsTranslate("main","LID_1331")+"\n" +
                qsTranslate("main","LID_1332")+"\n" +
                qsTranslate("main","LID_1333")+"\n" +
                qsTranslate("main","LID_1334")+"\n" +
                qsTranslate("main","LID_1335")+"\n" +
                qsTranslate("main","LID_1336")+"\n" +
                qsTranslate("main","LID_1337")+"\n" +
                qsTranslate("main","LID_1338")+"\n" +
                qsTranslate("main","LID_1339")+"\n" +
                qsTranslate("main","LID_1340")+"\n" +
                qsTranslate("main","LID_1341")+"\n" +
                qsTranslate("main","LID_1342")+"\n" +
                qsTranslate("main","LID_1343")+"\n" +
                qsTranslate("main","LID_1344")+"\n" +
                qsTranslate("main","LID_1346")+"\n" +
                qsTranslate("main","LID_1347")+"\n" +
                qsTranslate("main","LID_1348")+"\n" +
                qsTranslate("main","LID_1349")+"\n" +
                qsTranslate("main","LID_1350")+"\n" +
                qsTranslate("main","LID_1352")+"\n" +
                qsTranslate("main","LID_1353")+"\n" +
                qsTranslate("main","LID_1354")+"\n" +
                qsTranslate("main","LID_1355")+"\n" +
                qsTranslate("main","LID_1356")+"\n" +
                qsTranslate("main","LID_1357")+"\n" +
                qsTranslate("main","LID_1358")+"\n" +
                qsTranslate("main","LID_1359")+"\n" +
                qsTranslate("main","LID_1360")+"\n" +
                qsTranslate("main","LID_1361")+"\n" +
                qsTranslate("main","LID_1362")+"\n" +
                qsTranslate("main","LID_1363")+"\n" +
                qsTranslate("main","LID_1364")+"\n" +
                qsTranslate("main","LID_1365")+"\n" +
                qsTranslate("main","LID_1366")+"\n" +
                qsTranslate("main","LID_1367")+"\n" +
                qsTranslate("main","LID_1368")+"\n" +
                qsTranslate("main","LID_1369")+"\n" +
                qsTranslate("main","LID_1370")+"\n" +
                qsTranslate("main","LID_1371")+"\n" +
                qsTranslate("main","LID_1372")+"\n" +
                qsTranslate("main","LID_1373")+"\n" +
                qsTranslate("main","LID_1374")+"\n" +
                qsTranslate("main","LID_1376")+"\n" +
                qsTranslate("main","LID_1377")+"\n" +
                qsTranslate("main","LID_1378")+"\n" +
                qsTranslate("main","LID_1379")+"\n" +
                qsTranslate("main","LID_1380")+"\n" +
                qsTranslate("main","LID_1381")+"\n" +
                qsTranslate("main","LID_1384")+"\n" +
                qsTranslate("main","LID_1385")+"\n" +
                qsTranslate("main","LID_1386")+"\n" +
                qsTranslate("main","LID_1387")+"\n" +
                qsTranslate("main","LID_1388")+"\n" +
                qsTranslate("main","LID_1389")+"\n" +
                qsTranslate("main","LID_1390")+"\n" +
                qsTranslate("main","LID_1391")+"\n" +
                qsTranslate("main","LID_1392")+"\n" +
                qsTranslate("main","LID_1393")+"\n" +
                qsTranslate("main","LID_1395")+"\n" +
                qsTranslate("main","LID_1396")+"\n" +
                qsTranslate("main","LID_1397")+"\n" +
                qsTranslate("main","LID_1398")+"\n" +
                qsTranslate("main","LID_1399")+"\n" +
                qsTranslate("main","LID_1400")+"\n" +
                qsTranslate("main","LID_1401")+"\n" +
                qsTranslate("main","LID_1402")+"\n" +
                qsTranslate("main","LID_1403")+"\n" +
                qsTranslate("main","LID_1404")+"\n" +
                qsTranslate("main","LID_1405")+"\n" +
                qsTranslate("main","LID_1406")+"\n" +
                qsTranslate("main","LID_1407")+"\n" +
                qsTranslate("main","LID_1408")+"\n" +
                qsTranslate("main","LID_1409")+"\n" +
                qsTranslate("main","LID_1410")+"\n" +
                qsTranslate("main","LID_1411")+"\n" +
                qsTranslate("main","LID_1412")+"\n" +
                qsTranslate("main","LID_1413")+"\n" +
                qsTranslate("main","LID_1415")+"\n" +
                qsTranslate("main","LID_1416")+"\n" +
                qsTranslate("main","LID_1417")+"\n" +
                qsTranslate("main","LID_1418")+"\n" +
                qsTranslate("main","LID_1419")+"\n" +
                qsTranslate("main","LID_1420")+"\n" +
                qsTranslate("main","LID_1421")+"\n" +
                qsTranslate("main","LID_1422")+"\n" +
                qsTranslate("main","LID_1423")+"\n" +
                qsTranslate("main","LID_1424")+"\n" +
                qsTranslate("main","LID_1425")+"\n" +
                qsTranslate("main","LID_1426")+"\n" +
                qsTranslate("main","LID_1427")+"\n" +
                qsTranslate("main","LID_1428")+"\n" +
                qsTranslate("main","LID_1429")+"\n" +
                qsTranslate("main","LID_1430")+"\n" +
                qsTranslate("main","LID_1432")+"\n" +
                qsTranslate("main","LID_1433")+"\n" +
                qsTranslate("main","LID_1434")+"\n" +
                qsTranslate("main","LID_1435")+"\n" +
                qsTranslate("main","LID_1436")+"\n" +
                qsTranslate("main","LID_1437")+"\n" +
                qsTranslate("main","LID_1438")+"\n" +
                qsTranslate("main","LID_1439")+"\n" +
                qsTranslate("main","LID_1440")+"\n" +
                qsTranslate("main","LID_1441")+"\n" +
                qsTranslate("main","LID_1442")+"\n" +
                qsTranslate("main","LID_1443")+"\n" +
                qsTranslate("main","LID_1444")+"\n" +
                qsTranslate("main","LID_1445")+"\n" +
                qsTranslate("main","LID_1446")+"\n" +
                qsTranslate("main","LID_1447")+"\n" +
                qsTranslate("main","LID_1448")+"\n" +
                qsTranslate("main","LID_1450")+"\n" +
                qsTranslate("main","LID_1451")+"\n" +
                qsTranslate("main","LID_1452")+"\n" +
                qsTranslate("main","LID_1453")+"\n" +
                qsTranslate("main","LID_1454")+"\n" +
                qsTranslate("main","LID_1455")+"\n" +
                qsTranslate("main","LID_1456")+"\n" +
                qsTranslate("main","LID_1457")+"\n" +
                qsTranslate("main","LID_1458")+"\n" +
                qsTranslate("main","LID_1459")+"\n" +
                qsTranslate("main","LID_1460")+"\n" +
                qsTranslate("main","LID_1461")+"\n" +
                qsTranslate("main","LID_1462")+"\n" +
                qsTranslate("main","LID_1464")+"\n" +
                qsTranslate("main","LID_1465")+"\n" +
                qsTranslate("main","LID_1466")+"\n" +
                qsTranslate("main","LID_1467")+"\n" +
                qsTranslate("main","LID_1468")+"\n" +
                qsTranslate("main","LID_1469")+"\n" +
                qsTranslate("main","LID_1471")+"\n" +
                qsTranslate("main","LID_1472")+"\n" +
                qsTranslate("main","LID_1473")+"\n" +
                qsTranslate("main","LID_1474")+"\n" +
                qsTranslate("main","LID_1475")+"\n" +
                qsTranslate("main","LID_1476")+"\n" +
                qsTranslate("main","LID_1478")+"\n" +
                qsTranslate("main","LID_1479")+"\n" +
                qsTranslate("main","LID_1480")+"\n" +
                qsTranslate("main","LID_1481")+"\n" +
                qsTranslate("main","LID_1482")+"\n" +
                qsTranslate("main","LID_1483")+"\n" +
                qsTranslate("main","LID_1484")+"\n" +
                qsTranslate("main","LID_1485")+"\n" +
                qsTranslate("main","LID_1486")+"\n" +
                qsTranslate("main","LID_1487")+"\n" +
                qsTranslate("main","LID_1488")+"\n" +
                qsTranslate("main","LID_1489")+"\n" +
                qsTranslate("main","LID_1490")+"\n" +
                qsTranslate("main","LID_1491")+"\n" +
                qsTranslate("main","LID_1492")+"\n" +
                qsTranslate("main","LID_1493")+"\n" +
                qsTranslate("main","LID_1494")+"\n" +
                qsTranslate("main","LID_1495")+"\n" +
                qsTranslate("main","LID_1496")+"\n" +
                qsTranslate("main","LID_1497")+"\n" +
                qsTranslate("main","LID_1498")+"\n" +
                qsTranslate("main","LID_1499")+"\n" +
                qsTranslate("main","LID_1502")+"\n" +
                qsTranslate("main","LID_1504")+"\n" +
                qsTranslate("main","LID_1505")+"\n" +
                qsTranslate("main","LID_1506")+"\n" +
                qsTranslate("main","LID_1507")+"\n" +
                qsTranslate("main","LID_1509")+"\n" +
                qsTranslate("main","LID_1510")+"\n" +
                qsTranslate("main","LID_1511")+"\n" +
                qsTranslate("main","LID_1513")+"\n" +
                qsTranslate("main","LID_1514")+"\n" +
                qsTranslate("main","LID_1515")+"\n" +
                qsTranslate("main","LID_1516")+"\n" +
                qsTranslate("main","LID_1517")+"\n" +
                qsTranslate("main","LID_1518")+"\n" +
                qsTranslate("main","LID_1519")+"\n" +
                qsTranslate("main","LID_1520")+"\n" +
                qsTranslate("main","LID_1521")+"\n" +
                qsTranslate("main","LID_1524")+"\n" +
                qsTranslate("main","LID_1525")+"\n" +
                qsTranslate("main","LID_1527")+"\n" +
                qsTranslate("main","LID_1528")+"\n" +
                qsTranslate("main","LID_1529")+"\n" +
                qsTranslate("main","LID_1530")+"\n" +
                qsTranslate("main","LID_1531")+"\n" +
                qsTranslate("main","LID_1532")+"\n" +
                qsTranslate("main","LID_1533")+"\n" +
                qsTranslate("main","LID_1535")+"\n" +
                qsTranslate("main","LID_1536")+"\n" +
                qsTranslate("main","LID_1537")+"\n" +
                qsTranslate("main","LID_1538")+"\n" +
                qsTranslate("main","LID_1539")+"\n" +
                qsTranslate("main","LID_1540")+"\n" +
                qsTranslate("main","LID_1541")+"\n" +
                qsTranslate("main","LID_1542")+"\n" +
                qsTranslate("main","LID_1543")+"\n" +
                qsTranslate("main","LID_1544")+"\n" +
                qsTranslate("main","LID_1555")+"\n" +
                qsTranslate("main","LID_1556")+"\n" +
                qsTranslate("main","LID_1557")+"\n" +
                qsTranslate("main","LID_1558")+"\n" +
                qsTranslate("main","LID_1559")+"\n" +
                qsTranslate("main","LID_1560")+"\n" +
                qsTranslate("main","LID_1563")+"\n" +
                qsTranslate("main","LID_1564")+"\n" +
                qsTranslate("main","LID_1565")+"\n" +
                qsTranslate("main","LID_1567")+"\n" +
                qsTranslate("main","LID_1569")+"\n" +
                qsTranslate("main","LID_1570")+"\n" +
                qsTranslate("main","LID_1571")+"\n" +
                qsTranslate("main","LID_1572")+"\n" +
                qsTranslate("main","LID_1573")+"\n" +
                qsTranslate("main","LID_1574")+"\n" +
                qsTranslate("main","LID_1575")+"\n" +
                qsTranslate("main","LID_1576")+"\n" +
                qsTranslate("main","LID_1577")+"\n" +
                qsTranslate("main","LID_1578")+"\n" +
                qsTranslate("main","LID_1579")+"\n" +
                qsTranslate("main","LID_1580")+"\n" +
                qsTranslate("main","LID_1581")+"\n" +
                qsTranslate("main","LID_1582")+"\n" +
                qsTranslate("main","LID_1583")+"\n" +
                qsTranslate("main","LID_1584")+"\n" +
                qsTranslate("main","LID_1585")+"\n" +
                qsTranslate("main","LID_1586")+"\n" +
                qsTranslate("main","LID_1587")+"\n" +
                qsTranslate("main","LID_1588")+"\n" +
                qsTranslate("main","LID_1591")+"\n" +
                qsTranslate("main","LID_1592")+"\n" +
                qsTranslate("main","LID_1593")+"\n" +
                qsTranslate("main","LID_1594")+"\n" +
                qsTranslate("main","LID_1595")+"\n" +
                qsTranslate("main","LID_1596")+"\n" +
                qsTranslate("main","LID_1597")+"\n" +
                qsTranslate("main","LID_1598")+"\n" +
                qsTranslate("main","LID_1599")+"\n" +
                qsTranslate("main","LID_1600")+"\n" +
                qsTranslate("main","LID_1601")+"\n" +
                qsTranslate("main","LID_1602")+"\n" +
                qsTranslate("main","LID_1603")+"\n" +
                qsTranslate("main","LID_1604")+"\n" +
                qsTranslate("main","LID_1605")+"\n" +
                qsTranslate("main","LID_1606")+"\n" +
                qsTranslate("main","LID_1607")+"\n" +
                qsTranslate("main","LID_1608")+"\n" +
                qsTranslate("main","LID_1609")+"\n" +
                qsTranslate("main","LID_1610")+"\n" +
                qsTranslate("main","LID_1611")+"\n" +
                qsTranslate("main","LID_1612")+"\n" +
                qsTranslate("main","LID_1613")+"\n" +
                qsTranslate("main","LID_1614")+"\n" +
                qsTranslate("main","LID_1615")+"\n" +
                qsTranslate("main","LID_1616")+"\n" +
                qsTranslate("main","LID_1617")+"\n" +
                qsTranslate("main","LID_1618")+"\n" +
                qsTranslate("main","LID_1619")+"\n" +
                qsTranslate("main","LID_1620")+"\n" +
                qsTranslate("main","LID_1621")+"\n" +
                qsTranslate("main","LID_1622")+"\n" +
                qsTranslate("main","LID_1623")+"\n" +
                qsTranslate("main","LID_1624")+"\n" +
                qsTranslate("main","LID_1625")+"\n" +
                qsTranslate("main","LID_1626")+"\n" +
                qsTranslate("main","LID_1627")+"\n" +
                qsTranslate("main","LID_1628")+"\n" +
                qsTranslate("main","LID_1629")+"\n" +
                qsTranslate("main","LID_1630")+"\n" +
                qsTranslate("main","LID_1631")+"\n" +
                qsTranslate("main","LID_1632")+"\n" +
                qsTranslate("main","LID_1633")+"\n" +
                qsTranslate("main","LID_1634")+"\n" +
                qsTranslate("main","LID_1635")+"\n" +
                qsTranslate("main","LID_1637")+"\n" +
                qsTranslate("main","LID_1640")+"\n" +
                qsTranslate("main","LID_1641")+"\n" +
                qsTranslate("main","LID_1642")+"\n" +
                qsTranslate("main","LID_1643")+"\n" +
                qsTranslate("main","LID_1644")+"\n" +
                qsTranslate("main","LID_1645")+"\n" +
                qsTranslate("main","LID_1646")+"\n" +
                qsTranslate("main","LID_1649")+"\n" +
                qsTranslate("main","LID_1650")+"\n" +
                qsTranslate("main","LID_1651")+"\n" +
                qsTranslate("main","LID_1652")+"\n" +
                qsTranslate("main","LID_1653")+"\n" +
                qsTranslate("main","LID_1654")+"\n" +
                qsTranslate("main","LID_1655")+"\n" +
                qsTranslate("main","LID_1656")+"\n" +
                qsTranslate("main","LID_1657")+"\n" +
                qsTranslate("main","LID_1658")+"\n" +
                qsTranslate("main","LID_1659")+"\n" +
                qsTranslate("main","LID_1660")+"\n" +
                qsTranslate("main","LID_1661")+"\n" +
                qsTranslate("main","LID_1662")+"\n" +
                qsTranslate("main","LID_1663")+"\n" +
                qsTranslate("main","LID_1664")+"\n" +
                qsTranslate("main","LID_1665")+"\n" +
                qsTranslate("main","LID_1666")+"\n" +
                qsTranslate("main","LID_1667")+"\n" +
                qsTranslate("main","LID_1668")+"\n" +
                qsTranslate("main","LID_1669")+"\n" +
                qsTranslate("main","LID_1670")+"\n" +
                qsTranslate("main","LID_1672")+"\n" +
                qsTranslate("main","LID_1673")+"\n" +
                qsTranslate("main","LID_1674")+"\n" +
                qsTranslate("main","LID_1675")+"\n" +
                qsTranslate("main","LID_1676")+"\n" +
                qsTranslate("main","LID_1677")+"\n" +
                qsTranslate("main","LID_1678")+"\n" +
                qsTranslate("main","LID_1679")+"\n" +
                qsTranslate("main","LID_1680")+"\n" +
                qsTranslate("main","LID_1681")+"\n" +
                qsTranslate("main","LID_1682")+"\n" +
                qsTranslate("main","LID_1683")+"\n" +
                qsTranslate("main","LID_1684")+"\n" +
                qsTranslate("main","LID_1685")+"\n" +
                qsTranslate("main","LID_1686")+"\n" +
                qsTranslate("main","LID_1687")+"\n" +
                qsTranslate("main","LID_1688")+"\n" +
                qsTranslate("main","LID_1689")+"\n" +
                qsTranslate("main","LID_1690")+"\n" +
                qsTranslate("main","LID_1691")+"\n" +
                qsTranslate("main","LID_1692")+"\n" +
                qsTranslate("main","LID_1693")+"\n" +
                qsTranslate("main","LID_1694")+"\n" +
                qsTranslate("main","LID_1695")+"\n" +
                qsTranslate("main","LID_1701")+"\n" +
                qsTranslate("main","LID_1702")+"\n" +
                qsTranslate("main","LID_1703")+"\n" +
                qsTranslate("main","LID_1704")+"\n" +
                qsTranslate("main","LID_1705")+"\n" +
                qsTranslate("main","LID_1706")+"\n" +
                qsTranslate("main","LID_1707")+"\n" +
                qsTranslate("main","LID_1708")+"\n" +
                qsTranslate("main","LID_1709")+"\n" +
                qsTranslate("main","LID_1710")+"\n" +
                qsTranslate("main","LID_1711")+"\n" +
                qsTranslate("main","LID_1712")+"\n" +
                qsTranslate("main","LID_1713")+"\n" +
                qsTranslate("main","LID_1714")+"\n" +
                qsTranslate("main","LID_1715")+"\n" +
                qsTranslate("main","LID_1716")+"\n" +
                qsTranslate("main","LID_1717")+"\n" +
                qsTranslate("main","LID_1718")+"\n" +
                qsTranslate("main","LID_1719")+"\n" +
                qsTranslate("main","LID_1720")+"\n" +
                qsTranslate("main","LID_1721")+"\n" +
                qsTranslate("main","LID_1722")+"\n" +
                qsTranslate("main","LID_1723")+"\n" +
                qsTranslate("main","LID_1724")+"\n" +
                qsTranslate("main","LID_1725")+"\n" +
                qsTranslate("main","LID_1726")+"\n" +
                qsTranslate("main","LID_1727")+"\n" +
                qsTranslate("main","LID_1728")+"\n" +
                qsTranslate("main","LID_1729")+"\n" +
                qsTranslate("main","LID_1730")+"\n" +
                qsTranslate("main","LID_1731")+"\n" +
                qsTranslate("main","LID_1732")+"\n" +
                qsTranslate("main","LID_1733")+"\n" +
                qsTranslate("main","LID_1734")+"\n" +
                qsTranslate("main","LID_1735")+"\n" +
                qsTranslate("main","LID_1736")+"\n" +
                qsTranslate("main","LID_1737")+"\n" +
                qsTranslate("main","LID_1738")+"\n" +
                qsTranslate("main","LID_1739")+"\n" +
                qsTranslate("main","LID_1740")+"\n" +
                qsTranslate("main","LID_1741")+"\n" +
                qsTranslate("main","LID_1742")+"\n" +
                qsTranslate("main","LID_1744")+"\n" +
                qsTranslate("main","LID_1745")+"\n" +
                qsTranslate("main","LID_1746")+"\n" +
                qsTranslate("main","LID_1748")+"\n" +
                qsTranslate("main","LID_1749")+"\n" +
                qsTranslate("main","LID_1750")+"\n" +
                qsTranslate("main","LID_1751")+"\n" +
                qsTranslate("main","LID_1752")+"\n" +
                qsTranslate("main","LID_1753")+"\n" +
                qsTranslate("main","LID_1754")+"\n" +
                qsTranslate("main","LID_1755")+"\n" +
                qsTranslate("main","LID_1756")+"\n" +
                qsTranslate("main","LID_1757")+"\n" +
                qsTranslate("main","LID_1758")+"\n" +
                qsTranslate("main","LID_1759")+"\n" +
                qsTranslate("main","LID_1760")+"\n" +
                qsTranslate("main","LID_1761")+"\n" +
                qsTranslate("main","LID_1762")+"\n" +
                qsTranslate("main","LID_1763")+"\n" +
                qsTranslate("main","LID_1764")+"\n" +
                qsTranslate("main","LID_1765")+"\n" +
                qsTranslate("main","LID_1766")+"\n" +
                qsTranslate("main","LID_1778")+"\n" +
                qsTranslate("main","LID_1779")+"\n" +
                qsTranslate("main","LID_1780")+"\n" +
                qsTranslate("main","LID_1781")+"\n" +
                qsTranslate("main","LID_1782")+"\n" +
                qsTranslate("main","LID_1783")+"\n" +
                qsTranslate("main","LID_1785")+"\n" +
                qsTranslate("main","LID_1786")+"\n" +
                qsTranslate("main","LID_1787")+"\n" +
                qsTranslate("main","LID_1788")+"\n" +
                qsTranslate("main","LID_1789")+"\n" +
                qsTranslate("main","LID_1790")+"\n" +
                qsTranslate("main","LID_1791")+"\n" +
                qsTranslate("main","LID_1792")+"\n" +
                qsTranslate("main","LID_1793")+"\n" +
                qsTranslate("main","LID_1794")+"\n" +
                qsTranslate("main","LID_1795")+"\n" +
                qsTranslate("main","LID_1796")+"\n" +
                qsTranslate("main","LID_1797")+"\n" +
                qsTranslate("main","LID_1798")+"\n" +
                qsTranslate("main","LID_1799")+"\n" +
                qsTranslate("main","LID_1800")+"\n" +
                qsTranslate("main","LID_1801")+"\n" +
                qsTranslate("main","LID_1802")+"\n" +
                qsTranslate("main","LID_1803")+"\n" +
                qsTranslate("main","LID_1804")+"\n" +
                qsTranslate("main","LID_1805")+"\n" +
                qsTranslate("main","LID_1806")+"\n" +
                qsTranslate("main","LID_1807")+"\n" +
                qsTranslate("main","LID_1808")+"\n" +
                qsTranslate("main","LID_1809")+"\n" +
                qsTranslate("main","LID_1810")+"\n" +
                qsTranslate("main","LID_1811")+"\n" +
                qsTranslate("main","LID_1812")+"\n" +
                qsTranslate("main","LID_1813")+"\n" +
                qsTranslate("main","LID_1814")+"\n" +
                qsTranslate("main","LID_1815")+"\n" +
                qsTranslate("main","LID_1816")+"\n" +
                qsTranslate("main","LID_1817")+"\n" +
                qsTranslate("main","LID_1818")+"\n" +
                qsTranslate("main","LID_1819")+"\n" +
                qsTranslate("main","LID_1820")+"\n" +
                qsTranslate("main","LID_1821")+"\n" +
                qsTranslate("main","LID_1822")+"\n" +
                qsTranslate("main","LID_1823")+"\n" +
                qsTranslate("main","LID_1824")+"\n" +
                qsTranslate("main","LID_1825")+"\n" +
                qsTranslate("main","LID_1826")+"\n" +
                qsTranslate("main","LID_1827")+"\n" +
                qsTranslate("main","LID_1828")+"\n" +
                qsTranslate("main","LID_1829")+"\n" +
                qsTranslate("main","LID_1830")+"\n" +
                qsTranslate("main","LID_1831")+"\n" +
                qsTranslate("main","LID_1832")+"\n" +
                qsTranslate("main","LID_1833")+"\n" +
                qsTranslate("main","LID_1834")+"\n" +
                qsTranslate("main","LID_1835")+"\n" +
                qsTranslate("main","LID_1836")+"\n" +
                qsTranslate("main","LID_1837")+"\n" +
                qsTranslate("main","LID_1838")+"\n" +
                qsTranslate("main","LID_1839")+"\n" +
                qsTranslate("main","LID_1840")+"\n" +
                qsTranslate("main","LID_1841")+"\n" +
                qsTranslate("main","LID_1842")+"\n" +
                qsTranslate("main","LID_1843")+"\n" +
                qsTranslate("main","LID_1844")+"\n" +
                qsTranslate("main","LID_1846")+"\n" +
                qsTranslate("main","LID_1847")+"\n" +
                qsTranslate("main","LID_1848")+"\n" +
                qsTranslate("main","LID_1849")+"\n" +
                qsTranslate("main","LID_1850")+"\n" +
                qsTranslate("main","LID_1851")+"\n" +
                qsTranslate("main","LID_1852")+"\n" +
                qsTranslate("main","LID_1855")+"\n" +
                qsTranslate("main","LID_1856")+"\n" +
                qsTranslate("main","LID_1857")+"\n" +
                qsTranslate("main","LID_1858")+"\n" +
                qsTranslate("main","LID_1859")+"\n" +
                qsTranslate("main","LID_1860")+"\n" +
                qsTranslate("main","LID_1861")+"\n" +
                qsTranslate("main","LID_1862")+"\n" +
                qsTranslate("main","LID_1863")+"\n" +
                qsTranslate("main","LID_1864")+"\n" +
                qsTranslate("main","LID_1865")+"\n" +
                qsTranslate("main","LID_1867")+"\n" +
                qsTranslate("main","LID_1868")+"\n" +
                qsTranslate("main","LID_1870")+"\n" +
                qsTranslate("main","LID_1871")+"\n" +
                qsTranslate("main","LID_1872")+"\n" +
                qsTranslate("main","LID_1873")+"\n" +
                qsTranslate("main","LID_1874")+"\n" +
                qsTranslate("main","LID_1875")+"\n" +
                qsTranslate("main","LID_1876")+"\n" +
                qsTranslate("main","LID_1877")+"\n" +
                qsTranslate("main","LID_1878")+"\n" +
                qsTranslate("main","LID_1879")+"\n" +
                qsTranslate("main","LID_1880")+"\n" +
                qsTranslate("main","LID_1881")+"\n" +
                qsTranslate("main","LID_1882")+"\n" +
                qsTranslate("main","LID_1883")+"\n" +
                qsTranslate("main","LID_1884")+"\n" +
                qsTranslate("main","LID_1885")+"\n" +
                qsTranslate("main","LID_1886")+"\n" +
                qsTranslate("main","LID_1887")+"\n" +
                qsTranslate("main","LID_1888")+"\n" +
                qsTranslate("main","LID_1889")+"\n" +
                qsTranslate("main","LID_1890")+"\n" +
                qsTranslate("main","LID_1891")+"\n" +
                qsTranslate("main","LID_1892")+"\n" +
                qsTranslate("main","LID_1893")+"\n" +
                qsTranslate("main","LID_1894")+"\n" +
                qsTranslate("main","LID_1895")+"\n" +
                qsTranslate("main","LID_1896")+"\n" +
                qsTranslate("main","LID_1897")+"\n" +
                qsTranslate("main","LID_1898")+"\n" +
                qsTranslate("main","LID_1899")+"\n" +
                qsTranslate("main","LID_1900")+"\n" +
                qsTranslate("main","LID_1901")+"\n" +
                qsTranslate("main","LID_1902")+"\n" +
                qsTranslate("main","LID_1903")+"\n" +
                qsTranslate("main","LID_1904")+"\n" +
                qsTranslate("main","LID_1905")+"\n" +
                qsTranslate("main","LID_1906")+"\n" +
                qsTranslate("main","LID_1907")+"\n" +
                qsTranslate("main","LID_1908")+"\n" +
                qsTranslate("main","LID_1909")+"\n" +
                qsTranslate("main","LID_1910")+"\n" +
                qsTranslate("main","LID_1911")+"\n" +
                qsTranslate("main","LID_1912")+"\n" +
                qsTranslate("main","LID_1913")+"\n" +
                qsTranslate("main","LID_1914")+"\n" +
                qsTranslate("main","LID_1915")+"\n" +
                qsTranslate("main","LID_1916")+"\n" +
                qsTranslate("main","LID_1917")+"\n" +
                qsTranslate("main","LID_1918")+"\n" +
                qsTranslate("main","LID_1919")+"\n" +
                qsTranslate("main","LID_1920")+"\n" +
                qsTranslate("main","LID_1921")+"\n" +
                qsTranslate("main","LID_1922")+"\n" +
                qsTranslate("main","LID_1923")+"\n" +
                qsTranslate("main","LID_1924")+"\n" +
                qsTranslate("main","LID_1925")+"\n" +
                qsTranslate("main","LID_1926")+"\n" +
                qsTranslate("main","LID_1927")+"\n" +
                qsTranslate("main","LID_1928")+"\n" +
                qsTranslate("main","LID_1929")+"\n" +
                qsTranslate("main","LID_1930")+"\n" +
                qsTranslate("main","LID_1931")+"\n" +
                qsTranslate("main","LID_1932")+"\n" +
                qsTranslate("main","LID_1933")+"\n" +
                qsTranslate("main","LID_1934")+"\n" +
                qsTranslate("main","LID_1935")+"\n" +
                qsTranslate("main","LID_1936")+"\n" +
                qsTranslate("main","LID_1937")+"\n" +
                qsTranslate("main","LID_1938")+"\n" +
                qsTranslate("main","LID_1939")+"\n" +
                qsTranslate("main","LID_1940")+"\n" +
                qsTranslate("main","LID_1941")+"\n" +
                qsTranslate("main","LID_1942")+"\n" +
                qsTranslate("main","LID_1943")+"\n" +
                qsTranslate("main","LID_1944")+"\n" +
                qsTranslate("main","LID_1945")+"\n" +
                qsTranslate("main","LID_1946")+"\n" +
                qsTranslate("main","LID_1947")+"\n" +
                qsTranslate("main","LID_1948")+"\n" +
                qsTranslate("main","LID_1949")+"\n" +
                qsTranslate("main","LID_1950")+"\n" +
                qsTranslate("main","LID_1951")+"\n" +
                qsTranslate("main","LID_1952")+"\n" +
                qsTranslate("main","LID_1953")+"\n" +
                qsTranslate("main","LID_1954")+"\n" +
                qsTranslate("main","LID_1955")+"\n" +
                qsTranslate("main","LID_1956")+"\n" +
                qsTranslate("main","LID_1957")+"\n" +
                qsTranslate("main","LID_1958")+"\n" +
                qsTranslate("main","LID_1959")+"\n" +
                qsTranslate("main","LID_1960")+"\n" +
                qsTranslate("main","LID_1961")+"\n" +
                qsTranslate("main","LID_1962")+"\n" +
                qsTranslate("main","LID_1963")+"\n" +
                qsTranslate("main","LID_1964")+"\n" +
                qsTranslate("main","LID_1965")+"\n" +
                qsTranslate("main","LID_1966")+"\n" +
                qsTranslate("main","LID_1967")+"\n" +
                qsTranslate("main","LID_1968")+"\n" +
                qsTranslate("main","LID_1969")+"\n" +
                qsTranslate("main","LID_1970")+"\n" +
                qsTranslate("main","LID_1971")+"\n" +
                qsTranslate("main","LID_1972")+"\n" +
                qsTranslate("main","LID_1973")+"\n" +
                qsTranslate("main","LID_1974")+"\n" +
                qsTranslate("main","LID_1975")+"\n" +
                qsTranslate("main","LID_1976")+"\n" +
                qsTranslate("main","LID_1977")+"\n" +
                qsTranslate("main","LID_1978")+"\n" +
                qsTranslate("main","LID_1979")+"\n" +
                qsTranslate("main","LID_1980")+"\n" +
                qsTranslate("main","LID_1981")+"\n" +
                qsTranslate("main","LID_1982")+"\n" +
                qsTranslate("main","LID_1983")+"\n" +
                qsTranslate("main","LID_1984")+"\n" +
                qsTranslate("main","LID_1985")+"\n" +
                qsTranslate("main","LID_1986")+"\n" +
                qsTranslate("main","LID_1987")+"\n" +
                qsTranslate("main","LID_1988")+"\n" +
                qsTranslate("main","LID_1989")+"\n" +
                qsTranslate("main","LID_1990")+"\n" +
                qsTranslate("main","LID_1991")+"\n" +
                qsTranslate("main","LID_1992")+"\n" +
                qsTranslate("main","LID_1993")+"\n" +
                qsTranslate("main","LID_1994")+"\n" +
                qsTranslate("main","LID_1995")+"\n" +
                qsTranslate("main","LID_1996")+"\n" +
                qsTranslate("main","LID_1997")+"\n" +
                qsTranslate("main","LID_1998")+"\n" +
                qsTranslate("main","LID_1999")+"\n" +
                qsTranslate("main","LID_2000")+"\n" +
                qsTranslate("main","LID_2001")+"\n" +
                qsTranslate("main","LID_2002")+"\n" +
                qsTranslate("main","LID_2003")+"\n" +
                qsTranslate("main","LID_2004")+"\n" +
                qsTranslate("main","LID_2005")+"\n" +
                qsTranslate("main","LID_2006")+"\n" +
                qsTranslate("main","LID_2007")+"\n" +
                qsTranslate("main","LID_2008")+"\n" +
                qsTranslate("main","LID_2009")+"\n" +
                qsTranslate("main","LID_2010")+"\n" +
                qsTranslate("main","LID_2011")+"\n" +
                qsTranslate("main","LID_2012")+"\n" +
                qsTranslate("main","LID_2013")+"\n" +
                qsTranslate("main","LID_2014")+"\n" +
                qsTranslate("main","LID_2015")+"\n" +
                qsTranslate("main","LID_2016")+"\n" +
                qsTranslate("main","LID_2017")+"\n" +
                qsTranslate("main","LID_2018")+"\n" +
                qsTranslate("main","LID_2020")+"\n" +
                qsTranslate("main","LID_2021")+"\n" +
                qsTranslate("main","LID_2022")+"\n" +
                qsTranslate("main","LID_2023")+"\n" +
                qsTranslate("main","LID_2024")+"\n" +
                qsTranslate("main","LID_2025")+"\n" +
                qsTranslate("main","LID_2026")+"\n" +
                qsTranslate("main","LID_2027")+"\n" +
                qsTranslate("main","LID_2031")+"\n" +
                qsTranslate("main","LID_2032")+"\n" +
                qsTranslate("main","LID_2033")+"\n" +
                qsTranslate("main","LID_2034")+"\n" +
                qsTranslate("main","LID_2035")+"\n" +
                qsTranslate("main","LID_2036")+"\n" +
                qsTranslate("main","LID_2037")+"\n" +
                qsTranslate("main","LID_2038")+"\n" +
                qsTranslate("main","LID_2039")+"\n" +
                qsTranslate("main","LID_2040")+"\n" +
                qsTranslate("main","LID_2041")+"\n" +
                qsTranslate("main","LID_2042")+"\n" +
                qsTranslate("main","LID_2043")+"\n" +
                qsTranslate("main","LID_2044")+"\n" +
                qsTranslate("main","LID_2045")+"\n" +
                qsTranslate("main","LID_2046")+"\n" +
                qsTranslate("main","LID_2047")+"\n" +
                qsTranslate("main","LID_2048")+"\n" +
                qsTranslate("main","LID_2049")+"\n" +
                qsTranslate("main","LID_2050")+"\n" +
                qsTranslate("main","LID_2051")+"\n" +
                qsTranslate("main","LID_2052")+"\n" +
                qsTranslate("main","LID_2053")+"\n" +
                qsTranslate("main","LID_2054")+"\n" +
                qsTranslate("main","LID_2055")+"\n" +
                qsTranslate("main","LID_2056")+"\n" +
                qsTranslate("main","LID_2057")+"\n" +
                qsTranslate("main","LID_2058")+"\n" +
                qsTranslate("main","LID_2059")+"\n" +
                qsTranslate("main","LID_2060")+"\n" +
                qsTranslate("main","LID_2061")+"\n" +
                qsTranslate("main","LID_2062")+"\n" +
                qsTranslate("main","LID_2063")+"\n" +
                qsTranslate("main","LID_2064")+"\n" +
                qsTranslate("main","LID_2065")+"\n" +
                qsTranslate("main","LID_2066")+"\n" +
                qsTranslate("main","LID_2067")+"\n" +
                qsTranslate("main","LID_2068")+"\n" +
                qsTranslate("main","LID_2069")+"\n" +
                qsTranslate("main","LID_2070")+"\n" +
                qsTranslate("main","LID_2073")+"\n" +
                qsTranslate("main","LID_2074")+"\n" +
                qsTranslate("main","LID_2075")+"\n" +
                qsTranslate("main","LID_2076")+"\n" +
                qsTranslate("main","LID_2077")+"\n" +
                qsTranslate("main","LID_2078")+"\n" +
                qsTranslate("main","LID_2079")+"\n" +
                qsTranslate("main","LID_2080")+"\n" +
                qsTranslate("main","LID_2081")+"\n" +
                qsTranslate("main","LID_2082")+"\n" +
                qsTranslate("main","LID_2083")+"\n" +
                qsTranslate("main","LID_2084")+"\n" +
                qsTranslate("main","LID_2085")+"\n" +
                qsTranslate("main","LID_2086")+"\n" +
                qsTranslate("main","LID_2087")+"\n" +
                qsTranslate("main","LID_2088")+"\n" +
                qsTranslate("main","LID_2089")+"\n" +
                qsTranslate("main","LID_2090")+"\n" +
                qsTranslate("main","LID_2091")+"\n" +
                qsTranslate("main","LID_2092")+"\n" +
                qsTranslate("main","LID_2093")+"\n" +
                qsTranslate("main","LID_2094")+"\n" +
                qsTranslate("main","LID_2095")+"\n" +
                qsTranslate("main","LID_2096")+"\n" +
                qsTranslate("main","LID_2097")+"\n" +
                qsTranslate("main","LID_2098")+"\n" +
                qsTranslate("main","LID_2099")+"\n" +
                qsTranslate("main","LID_2100")+"\n" +
                qsTranslate("main","LID_2101")+"\n" +
                qsTranslate("main","LID_2102")+"\n" +
                qsTranslate("main","LID_2103")+"\n" +
                qsTranslate("main","LID_2104")+"\n" +
                qsTranslate("main","LID_2105")+"\n" +
                qsTranslate("main","LID_2106")+"\n" +
                qsTranslate("main","LID_2107")+"\n" +
                qsTranslate("main","LID_2108")+"\n" +
                qsTranslate("main","LID_2109")+"\n" +
                qsTranslate("main","LID_2110")+"\n" +
                qsTranslate("main","LID_2111")+"\n" +
                qsTranslate("main","LID_2112")+"\n" +
                qsTranslate("main","LID_2113")+"\n" +
                qsTranslate("main","LID_2114")+"\n" +
                qsTranslate("main","LID_2115")+"\n" +
                qsTranslate("main","LID_2116")+"\n" +
                qsTranslate("main","LID_2117")+"\n" +
                qsTranslate("main","LID_2118")+"\n" +
                qsTranslate("main","LID_2119")+"\n" +
                qsTranslate("main","LID_2120")+"\n" +
                qsTranslate("main","LID_2121")+"\n" +
                qsTranslate("main","LID_2122")+"\n" +
                qsTranslate("main","LID_2123")+"\n" +
                qsTranslate("main","LID_2124")+"\n" +
                qsTranslate("main","LID_2125")+"\n" +
                qsTranslate("main","LID_2126")+"\n" +
                qsTranslate("main","LID_2127")+"\n" +
                qsTranslate("main","LID_2128")+"\n" +
                qsTranslate("main","LID_2129")+"\n" +
                qsTranslate("main","LID_2130")+"\n" +
                qsTranslate("main","LID_2131")+"\n" +
                qsTranslate("main","LID_2132")+"\n" +
                qsTranslate("main","LID_2133")+"\n" +
                qsTranslate("main","LID_2134")+"\n" +
                qsTranslate("main","LID_2135")+"\n" +
                qsTranslate("main","LID_2136")+"\n" +
                qsTranslate("main","LID_2137")+"\n" +
                qsTranslate("main","LID_2138")+"\n" +
                qsTranslate("main","LID_2139")+"\n" +
                qsTranslate("main","LID_2140")+"\n" +
                qsTranslate("main","LID_2141")+"\n" +
                qsTranslate("main","LID_2142")+"\n" +
                qsTranslate("main","LID_2143")+"\n" +
                qsTranslate("main","LID_2144")+"\n" +
                qsTranslate("main","LID_2145")+"\n" +
                qsTranslate("main","LID_2146")+"\n" +
                qsTranslate("main","LID_2147")+"\n" +
                qsTranslate("main","LID_2148")+"\n" +
                qsTranslate("main","LID_2149")+"\n" +
                qsTranslate("main","LID_2150")+"\n" +
                qsTranslate("main","LID_2151")+"\n" +
                qsTranslate("main","LID_2152")+"\n" +
                qsTranslate("main","LID_2153")+"\n" +
                qsTranslate("main","LID_2154")+"\n" +
                qsTranslate("main","LID_2156")+"\n" +
                qsTranslate("main","LID_2157")+"\n" +
                qsTranslate("main","LID_2158")+"\n" +
                qsTranslate("main","LID_2159")+"\n" +
                qsTranslate("main","LID_2160")+"\n" +
                qsTranslate("main","LID_2161")+"\n" +
                qsTranslate("main","LID_2162")+"\n" +
                qsTranslate("main","LID_2163")+"\n" +
                qsTranslate("main","LID_2164")+"\n" +
                qsTranslate("main","LID_2165")+"\n" +
                qsTranslate("main","LID_2166")+"\n" +
                qsTranslate("main","LID_2167")+"\n" +
                qsTranslate("main","LID_2168")+"\n" +
                qsTranslate("main","LID_2169")+"\n" +
                qsTranslate("main","LID_2170")+"\n" +
                qsTranslate("main","LID_2171")+"\n" +
                qsTranslate("main","LID_2172")+"\n" +
                qsTranslate("main","LID_2173")+"\n" +
                qsTranslate("main","LID_2174")+"\n" +
                qsTranslate("main","LID_2175")+"\n" +
                qsTranslate("main","LID_2176")+"\n" +
                qsTranslate("main","LID_2177")+"\n" +
                qsTranslate("main","LID_2178")+"\n" +
                qsTranslate("main","LID_2179")+"\n" +
                qsTranslate("main","LID_2180")+"\n" +
                qsTranslate("main","LID_2181")+"\n" +
                qsTranslate("main","LID_2182")+"\n" +
                qsTranslate("main","LID_2183")+"\n" +
                qsTranslate("main","LID_2184")+"\n" +
                qsTranslate("main","LID_2185")+"\n" +
                qsTranslate("main","LID_2186")+"\n" +
                qsTranslate("main","LID_2187")+"\n" +
                qsTranslate("main","LID_2188")+"\n" +
                qsTranslate("main","LID_2189")+"\n" +
                qsTranslate("main","LID_2190")+"\n" +
                qsTranslate("main","LID_2191")+"\n" +
                qsTranslate("main","LID_2192")+"\n" +
                qsTranslate("main","LID_2193")+"\n" +
                qsTranslate("main","LID_2194")+"\n" +
                qsTranslate("main","LID_2195")+"\n" +
                qsTranslate("main","LID_2196")+"\n" +
                qsTranslate("main","LID_2197")+"\n" +
                qsTranslate("main","LID_2198")+"\n" +
                qsTranslate("main","LID_2199")+"\n" +
                qsTranslate("main","LID_2200")+"\n" +
                qsTranslate("main","LID_2201")+"\n" +
                qsTranslate("main","LID_2202")+"\n" +
                qsTranslate("main","LID_2203")+"\n" +
                qsTranslate("main","LID_2204")+"\n" +
                qsTranslate("main","LID_2205")+"\n" +
                qsTranslate("main","LID_2206")+"\n" +
                qsTranslate("main","LID_2207")+"\n" +
                qsTranslate("main","LID_2208")+"\n" +
                qsTranslate("main","LID_2209")+"\n" +
                qsTranslate("main","LID_2210")+"\n" +
                qsTranslate("main","LID_2211")+"\n" +
                qsTranslate("main","LID_2212")+"\n" +
                qsTranslate("main","LID_2213")+"\n" +
                qsTranslate("main","LID_2214")+"\n" +
                qsTranslate("main","LID_2215")+"\n" +
                qsTranslate("main","LID_2216")+"\n" +
                qsTranslate("main","LID_2217")+"\n" +
                qsTranslate("main","LID_2218")+"\n" +
                qsTranslate("main","LID_2219")+"\n" +
                qsTranslate("main","LID_2220")+"\n" +
                qsTranslate("main","LID_2221")+"\n" +
                qsTranslate("main","LID_2222")+"\n" +
                qsTranslate("main","LID_2223")+"\n" +
                qsTranslate("main","LID_2224")+"\n" +
                qsTranslate("main","LID_2225")+"\n" +
                qsTranslate("main","LID_2226")+"\n" +
                qsTranslate("main","LID_2227")+"\n" +
                qsTranslate("main","LID_2228")+"\n" +
                qsTranslate("main","LID_2229")+"\n" +
                qsTranslate("main","LID_2230")+"\n" +
                qsTranslate("main","LID_2231")+"\n" +
                qsTranslate("main","LID_2232")+"\n" +
                qsTranslate("main","LID_2233")+"\n" +
                qsTranslate("main","LID_2234")+"\n" +
                qsTranslate("main","LID_2235")+"\n" +
                qsTranslate("main","LID_2236")+"\n" +
                qsTranslate("main","LID_2237")+"\n" +
                qsTranslate("main","LID_2238")+"\n" +
                qsTranslate("main","LID_2239")+"\n" +
                qsTranslate("main","LID_2240")+"\n" +
                qsTranslate("main","LID_2241")+"\n" +
                qsTranslate("main","LID_2242")+"\n" +
                qsTranslate("main","LID_2243")+"\n" +
                qsTranslate("main","LID_2244")+"\n" +
                qsTranslate("main","LID_2245")+"\n" +
                qsTranslate("main","LID_2246")+"\n" +
                qsTranslate("main","LID_2247")+"\n" +
                qsTranslate("main","LID_2248")+"\n" +
                qsTranslate("main","LID_2255")+"\n" +
                qsTranslate("main","LID_2256")+"\n" +
                qsTranslate("main","LID_2257")+"\n" +
                qsTranslate("main","LID_2258")+"\n" +
                qsTranslate("main","LID_2260")+"\n" +
                qsTranslate("main","LID_2261")+"\n" +
                qsTranslate("main","LID_2262")+"\n" +
                qsTranslate("main","LID_2263")+"\n" +
                qsTranslate("main","LID_2264")+"\n" +
                qsTranslate("main","LID_2265")+"\n" +
                qsTranslate("main","LID_2266")+"\n" +
                qsTranslate("main","LID_2267")+"\n" +
                qsTranslate("main","LID_2268")+"\n" +
                qsTranslate("main","LID_2269")+"\n" +
                qsTranslate("main","LID_2270")+"\n" +
                qsTranslate("main","LID_2271")+"\n" +
                qsTranslate("main","LID_2272")+"\n" +
                qsTranslate("main","LID_2273")+"\n" +
                qsTranslate("main","LID_2274")+"\n" +
                qsTranslate("main","LID_2275")+"\n" +
                qsTranslate("main","LID_2276")+"\n" +
                qsTranslate("main","LID_2277")+"\n" +
                qsTranslate("main","LID_2278")+"\n" +
                qsTranslate("main","LID_2279")+"\n" +
                qsTranslate("main","LID_2280")+"\n" +
                qsTranslate("main","LID_2281")+"\n" +
                qsTranslate("main","LID_2282")+"\n" +
                qsTranslate("main","LID_2283")+"\n" +
                qsTranslate("main","LID_2284")+"\n" +
                qsTranslate("main","LID_2285")+"\n" +
                qsTranslate("main","LID_2286")+"\n" +
                qsTranslate("main","LID_2287")+"\n" +
                qsTranslate("main","LID_2288")+"\n" +
                qsTranslate("main","LID_2289")+"\n" +
                qsTranslate("main","LID_2290")+"\n" +
                qsTranslate("main","LID_2291")+"\n" +
                qsTranslate("main","LID_2292")+"\n" +
                qsTranslate("main","LID_2293")+"\n" +
                qsTranslate("main","LID_2294")+"\n" +
                qsTranslate("main","LID_2295")+"\n" +
                qsTranslate("main","LID_2296")+"\n" +
                qsTranslate("main","LID_2297")+"\n" +
                qsTranslate("main","LID_2298")+"\n" +
                qsTranslate("main","LID_2299")+"\n" +
                qsTranslate("main","LID_2300")+"\n" +
                qsTranslate("main","LID_2301")+"\n" +
                qsTranslate("main","LID_2302")+"\n" +
                qsTranslate("main","LID_2303")+"\n" +
                qsTranslate("main","LID_2304")+"\n" +
                qsTranslate("main","LID_2305")+"\n" +
                qsTranslate("main","LID_2306")+"\n" +
                qsTranslate("main","LID_2307")+"\n" +
                qsTranslate("main","LID_2308")+"\n" +
                qsTranslate("main","LID_2309")+"\n" +
                qsTranslate("main","LID_2310")+"\n" +
                qsTranslate("main","LID_2311")+"\n" +
                qsTranslate("main","LID_2312")+"\n" +
                qsTranslate("main","LID_2313")+"\n" +
                qsTranslate("main","LID_2314")+"\n" +
                qsTranslate("main","LID_2315")+"\n" +
                qsTranslate("main","LID_2316")+"\n" +
                qsTranslate("main","LID_2317")+"\n" +
                qsTranslate("main","LID_2318")+"\n" +
                qsTranslate("main","LID_2319")+"\n"
    }

    // Start translating the application window when the application was created
    Component.onCompleted: {
        retranslateUi();
    }
}
